Dev
IgorEzerskiy/shop pull request #1
Opened 2023-05-09 14:41 UTC by IgorEzerskiy

2023-05-12 22:19 UTC, PkQDark commented on main_app/models.py
> +        User.objects.select_for_update().filter(id=self.id).update(wallet=F('wallet') - amount)
Лишний запрос в базу данных, зачем он тут? почему нельзя просто сделать 
```
self.wallet -= amount
self.save()
```

2023-05-12 22:19 UTC, PkQDark commented on main_app/models.py
> +        Product.objects.select_for_update().filter(id=self.id).update(quantity=F('quantity') - amount)
Тоже самое что и с юзером

2023-05-12 22:19 UTC, PkQDark commented on main_app/models.py
> +        self.slug = slugify(self.title) + '-' + str(datetime.datetime.now().strftime("%Y-%m-%d-%H-%M"))
При апдейте будет менятся слаг, плохая практика

2023-05-12 22:19 UTC, PkQDark commented on main_app/models.py
>      product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
релейтед неймы оба названы максимально не адекватно и будут сбивать с толку

2023-05-12 22:19 UTC, PkQDark commented on main_app/views.py
> +class ProductCreateView(LoginRequiredMixin, CreateView):
Нет проверки на админа

2023-05-12 22:19 UTC, PkQDark commented on main_app/views.py
> +class ProductUpdateView(LoginRequiredMixin, UpdateView):
Опять же нет проверки на админа

2023-05-12 22:19 UTC, PkQDark commented on main_app/views.py
> +    extra_context = {'product_quantity': PurchaseForm()}
Название формы не адекватное и будет сбивать с толку

2023-05-12 22:19 UTC, PkQDark commented on main_app/views.py
> +    slug_url_kwarg = 'slug'
А зачем тут эта строка?)) если это и так дефолт

2023-05-12 22:19 UTC, PkQDark commented on main_app/views.py
> +    def form_valid(self, form):
Не запускал, но у меня очень сильные сомнения что это вообще запустится

2023-05-12 22:19 UTC, PkQDark commented on main_app/forms.py
> +            product = Product.objects.get(slug=self.slug)
Не хватает проверки что запрошена хотя бы одна единица товара

2023-05-12 22:19 UTC, PkQDark commented on main_app/forms.py
> +        except Product.DoesNotExist:
Трай делаешь на покупке) а отлавливаешь продукт)) херня какая-то))

2023-05-12 22:19 UTC, PkQDark commented on main_app/forms.py
> +            time_delta = datetime.timedelta(minutes=3)
Такие параметры как кол-во минут лучше хранить как переменную в сетингсах и потом импортировать) 
это не критично, но так было бы гораздно удобнее если тебе вдруг срочно надо поменять значение

2023-05-12 22:19 UTC, PkQDark commented on main_app/forms.py
> +        with transaction.atomic():
Зачем тебе атомик на одно действие)) и зачем вызывать сейв с фолсом?? он же просто не будет работать))

2023-06-02 22:16 UTC, PonomaryovVladyslav requested changes

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/serializers.py
> +    password = serializers.CharField(write_only=True)
Смена пароля  так работать не будет :)

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/serializers.py
> +    user = serializers.PrimaryKeyRelatedField(queryset=User.objects.all(), required=False)
А если не секрет зачем тут эта строчка?)

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/serializers.py
> +        datetime_now = datetime.datetime.utcnow().replace(tzinfo=datetime.timezone.utc)
Если что можно просто из джанго вытаскивать время и не любить мозги с таймзонами в таком виде.

from django.utils import timezone если панять не обманывает

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsAdminOrReadOnly]
А зачем тут два пермишена?) Только второго разве не хватит?)

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
Поздравляю, ты позволил пользователям удалять и редактировать друг друга, шик идея

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    filter_backends = [SearchFilter]
И ты таким образом позволяешь пользователям смотреть, удалять и редактировать покупки друг друга, еще одна шик идея))

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    http_method_names = ['get']
Где вы это взяли?) у лист вью и так описан только гет)

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    http_method_names = ['delete']
туда же

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    http_method_names = ['delete']
туда же

2023-06-02 22:16 UTC, PonomaryovVladyslav commented on main_app/api/resources.py
> +    def destroy(self, request, *args, **kwargs):
Почему не переписать perform_destroy? будет куда логичнее, хоть экономишь аж 2 строчки)) но структура будет лучше

2023-06-17 09:41 UTC, merged